### ISSUE TITLE
Repeatedly generating invites

### ISSUE THREAD

**Issue by jschuur** [lucasjgordon/slackform#1]
I ran into the problem we had the other day of it sending multiple invites to the same person, on an instance of my own for this (not techlondon related).

It doesn't seem to do it every time though. Manually running the background job sent me a new invite, but not when I did that twice in a row. All in all I got 4 invites within 25 minutes for a 5 minutes interval job, but once they were at least 8 minutes.

How does it decide if it's not yet sent an invite?

**Comment by lucasjgordon** [comment]
Hey Joost, how's it going? There's a time stamp param in the Typeform API call that retrieves new submissions within the last hour. So you need to run the job every hour. I may update it so you can specify the time period, but I figured one hour was reasonable. Let me know if this solves the issue!
